services:
  - type: web
    name: aura-pdf-summarizer
    env: python
    pythonVersion: "3.11"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
